spring:
  profiles: default
  someconf:
    hello: msg
    password: '{cipher}54c742351371241db3d1fd60fefaae4448c7db249098391549a37a14e6efaed5'
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery1.local:8761/eureka,http://discovery2.local:8762/eureka