spring:
  profiles: development
  someconf:
    hello: msg
    password: '{cipher}AQAq00CG4k5G04ak5IFtM4SAK41deBCZYK3zY3S1DfcWid/iP+OTgX3VH0KsjNp9+T+sRa8i2Dw6oulPBT3aZ+Kb1MGwFjdEMnwn8VGyWLIeNwsaH5l7zsR7gAzkNDDExTrPYzdFTOV54pysfB5Wexfq1NDR+CR9i6eudTw6z+ZxhKOp2U1NxXgPjOB21YKLqe1Xw8rt/6yfoljdMAcOKGDm+ocNL8MxYY4qhucvSK4Ad3mzPqqFpNuL3VX8B9LzwqZcvkjsKN1mXiVwwgVqmbhlZktHeNaGfxp9E1IxKoQ8u8aL8Hwm1wb7XYg2v8t4fwP1yWVvf2o8SLLWe+z+CjK/DCKFotmp4ys4E0gc4br1l0qFgsPJ6gAnxscd66/AlBY='
encrypt:
  key-store:
    location: file:///Users/mandoprog/workspace/awb-vente/poc-archi-2/config-service/server.jks
    password: keypass
    alias: configkey
    secret: keysecret

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery1.local:8761/eureka,http://discovery2.local:8762/eureka