spring:
  profiles: development
  someconf:
    hello: msg
    password: '{cipher}pass'
encrypt:
  key: allo

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery1.local:8761/eureka,http://discovery2.local:8762/eureka